todo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("todo_list.urls", namespace="todo_list"))
]

todo_list/urls.py
from django.urls import path

from todo_list.views import (
    TaskListView,
    TagListView,
    TaskCreateView,
    TaskUpdateView,
    TaskDeleteView,
    TagCreateView,
    TagUpdateView,
    TagDeleteView,
    TaskSwitcher,
)

urlpatterns = [
    path("", TaskListView.as_view(), name="todo"),
    path("create/", TaskCreateView.as_view(), name="task_create"),
    path("task/<int:pk>/update/", TaskUpdateView.as_view(), name="task-update"),
    path("task/<int:pk>/delete/", TaskDeleteView.as_view(), name="task-delete"),
    path(
        "task/<int:pk>/switch-task-is-done/",
        TaskSwitcher.as_view(),
        name="switch-task-is-done",
    ),
    path("tags/", TagListView.as_view(), name="tag-list"),
    path("tags/create/", TagCreateView.as_view(), name="tag-create"),
    path("tags/<int:pk>/update/", TagUpdateView.as_view(), name="tag-update"),
    path("tags/<int:pk>/delete/", TagDeleteView.as_view(), name="tag-delete"),
]

app_name = "todo_list"

todo_list/models.py
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Task(models.Model):
    content = models.CharField(max_length=255)
    date = models.DateTimeField(auto_now_add=True)
    deadline = models.DateTimeField(null=True, blank=True)
    is_done = models.BooleanField()
    tags = models.ManyToManyField(to=Tag, related_name="tasks")

    class Meta:
        ordering = ["is_done", "-date"]

todo_list/forms.py
from django import forms

from todo_list.models import Task, Tag


class TaskForm(forms.ModelForm):
    tags = forms.ModelMultipleChoiceField(
        queryset=Tag.objects.all(),
        widget=forms.CheckboxSelectMultiple
    )
    deadline = forms.DateField(widget=forms.SelectDateWidget, required=False)

    class Meta:
        model = Task
        fields = "__all__"

todo_list/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.views import generic, View

from todo_list.forms import TaskForm
from todo_list.models import Task, Tag


class TaskListView(generic.ListView):
    model = Task
    context_object_name = "task_list"
    paginate_by = 10
    template_name = "todo_list/index.html"


class TaskCreateView(generic.CreateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("todo_list:todo")


class TaskUpdateView(generic.UpdateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("todo_list:todo")


class TaskDeleteView(generic.DeleteView):
    model = Task
    fields = "__all__"
    success_url = reverse_lazy("todo_list:todo")


class TagListView(generic.ListView):
    model = Tag
    context_object_name = "tag_list"
    paginate_by = 10


class TagCreateView(generic.CreateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("todo_list:tag-list")


class TagUpdateView(generic.UpdateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("todo_list:tag-list")


class TagDeleteView(generic.DeleteView):
    model = Tag
    success_url = reverse_lazy("todo_list:tag-list")


class TaskSwitcher(View):

    @staticmethod
    def get(request, pk: int) -> HttpResponseRedirect:
        task = Task.objects.get(id=pk)
        task.is_done = not task.is_done
        task.save()
        return HttpResponseRedirect(reverse_lazy("todo_list:todo"))

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% block title %}<title>ToDo</title>{% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
          crossorigin="anonymous">
</head>

<body>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-2">

            {% block sidebar %}
                {% include "includes/sidebar.html" %}
            {% endblock %}

        </div>
        <div class="col-sm-10 ">

            {% block content %}{% endblock %}

            {% block pagination %}
                {% include "includes/pagination.html" %}
            {% endblock %}

        </div>
    </div>
</div>
</body>

</html>

templates/includes/pagination.html
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?page= {{ page_obj.previous_page_number }}" class="page-link">prev</a>
      </li>
    {% endif %}
    <li class="page-item active">
      <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
    </li>
    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?page= {{ page_obj.next_page_number }}" class="page-link">next</a>
      </li>
    {% endif %}
  </ul>
{% endif %}

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  <li class="list-group-item"><a href="{% url 'todo_list:todo' %}">Home</a></li>
  <li class="list-group-item"><a href="{% url 'todo_list:tag-list' %}">All tags</a></li>
</ul>

templates/todo_list/index.html
{% extends "base.html" %}

{% block content %}
  <h1>
    Task list:
    <a href="{% url 'todo_list:task_create' %}" class="btn btn-primary link-to-page">
      Create task
    </a>
  </h1>
  {% if task_list %}
  <table class="table">
    <tr>
      <th>Task</th>
      <th>Date of creation</th>
      <th>Dead line</th>
      <th>Done</th>
      <th>Update</th>
      <th>Delete</th>
      <th>Change status</th>
    </tr>

    {% for task in task_list %}
      <tr>
      <td><h5>{{ task.content }}</h5></td>
      <td>{{ task.date }}</td>
      <td>{{ task.deadline }}</td>
      <td>{{ task.is_done }}</td>
      <td><a href="{% url 'todo_list:task-update' pk=task.id %}" class="btn btn-primary link-to-page">Update</a></td>
      <td><a href="{% url 'todo_list:task-delete' pk=task.id %}" class="btn btn-danger link-to-page">Delete</a></td>
      <td>
        {% if task.is_done %}
          <a href="{% url 'todo_list:switch-task-is-done' pk=task.id %}" class="btn btn-outline-secondary link-to-page">Undo</a>
        {% else %}
          <a href="{% url 'todo_list:switch-task-is-done' pk=task.id %}" class="btn btn-outline-success link-to-page">Complete</a>
        {% endif %}
      </td>
      </tr>
    {% endfor %}
  </table>
  {% else %}
    <h4>There are no task yet</h4>
  {% endif %}
{% endblock %}

templates/todo_list/tag_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete tag?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/todo_list/tag_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} tag</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form.as_p }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/todo_list/tag_list.html
{% extends "base.html" %}

{% block title %}
  <title>Tag List</title>
{% endblock %}
{% block content %}
  <h1>
    Tag list:
    <a href="{% url 'todo_list:tag-create' %}" class="btn btn-primary link-to-page">
      Create tag
    </a>
  </h1>
  {% if tag_list %}
    <table class="table">
      <tr>
        <th>Tag</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>
      {% for tag in tag_list %}
      <tr>
        <td>{{ tag }}</td>
        <td><a href="{% url 'todo_list:tag-update' pk=tag.id %}" class="btn btn-primary link-to-page">Update</a></td>
        <td><a href="{% url 'todo_list:tag-delete' pk=tag.id %}" class="btn btn-danger link-to-page">Delete</a></td>
      </tr>

    {% endfor %}
    </table>
  {% else %}
    <h4>There are no any tag yet</h4>
  {% endif %}
{% endblock %}

templates/todo_list/task_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete task?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/todo_list/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} task</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form.as_p }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}